name: super_network_image
description: A Flutter widget for loading and caching network images, supporting both raster and SVG formats with advanced caching capabilities.
version: 0.0.1
homepage: https://github.com/ayush221b/super_network_image
repository: https://github.com/ayush221b/super_network_image

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  http: ^1.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: